services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    env_file: .env
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

  redis:
    image: redis:latest
    container_name: redis
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  kafka_data:
  redis_data: